# STAGE 1: Build Stage (Thulo Node environment ma React code compile garne)
FROM node:20-alpine AS builder

WORKDIR /frontend

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# STAGE 2: Production Stage (Heavy Node lai fyakera, pure Nginx server ma static files matra rakhne)
FROM nginx:alpine

# Custom Nginx config copy garne
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Stage 1 (builder) ma baneko dist folder lai Nginx bhitra copy garne
COPY --from=builder /frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]